from datetime import date

from app.domain import Book, Member


# Seed data copied from analysis/raw-materials/books.csv for the basic MVP.
BOOKS = [
    Book(
        bookId="B001",
        title="The Great Gatsby",
        category="fiction",
        referenceOnly=False,
        available=True,
    ),
    Book(
        bookId="B002",
        title="Introduction to Data Science",
        category="education",
        referenceOnly=False,
        available=True,
    ),
    Book(
        bookId="B003",
        title="Oxford English Dictionary",
        category="reference",
        referenceOnly=True,
        available=True,
    ),
    Book(
        bookId="B004",
        title="World History Atlas",
        category="reference",
        referenceOnly=True,
        available=True,
    ),
    Book(
        bookId="B005",
        title="Modern JavaScript Explained",
        category="technology",
        referenceOnly=False,
        available=True,
    ),
    Book(
        bookId="B006",
        title="The Art of Photography",
        category="arts",
        referenceOnly=False,
        available=False,
    ),
    Book(
        bookId="B007",
        title="Advanced Economics",
        category="education",
        referenceOnly=False,
        available=True,
    ),
    Book(
        bookId="B008",
        title="Digital Accessibility Guidelines",
        category="education",
        referenceOnly=False,
        available=True,
    ),
    Book(
        bookId="B009",
        title="Introduction to Philosophy",
        category="non-fiction",
        referenceOnly=False,
        available=False,
    ),
    Book(
        bookId="B010",
        title="Children's Story Hour Collection",
        category="children",
        referenceOnly=False,
        available=True,
    ),
    Book(
        bookId="B011",
        title="Urban Planning Basics",
        category="non-fiction",
        referenceOnly=False,
        available=True,
    ),
    Book(
        bookId="B012",
        title="European History 1900-1950",
        category="history",
        referenceOnly=False,
        available=True,
    ),
    Book(
        bookId="B013",
        title="Local City History Compendium",
        category="history",
        referenceOnly=True,
        available=True,
    ),
    Book(
        bookId="B014",
        title="Learning Python the Hard Way",
        category="technology",
        referenceOnly=False,
        available=True,
    ),
    Book(
        bookId="B015",
        title="Creative Writing Handbook",
        category="arts",
        referenceOnly=False,
        available=True,
    ),
]


# Seed data copied from analysis/raw-materials/members.csv for the basic MVP.
MEMBERS = [
    Member(
        memberId="M001",
        firstName="Emily",
        lastName="Johnson",
        email="emily.johnson@example.org",
        memberType="adult",
        suspendedUntil=None,
        createdAt=date(2019, 3, 12),
    ),
    Member(
        memberId="M002",
        firstName="Daniel",
        lastName="Smith",
        email="daniel.smith@example.org",
        memberType="student",
        suspendedUntil=None,
        createdAt=date(2023, 9, 1),
    ),
    Member(
        memberId="M003",
        firstName="Michael",
        lastName="Brown",
        email="michael.brown@example.org",
        memberType="adult",
        suspendedUntil=date(2026, 2, 15),
        createdAt=date(2018, 6, 24),
    ),
    Member(
        memberId="M004",
        firstName="Sophie",
        lastName="Williams",
        email="sophie.williams@example.org",
        memberType="student",
        suspendedUntil=date(2025, 11, 30),
        createdAt=date(2024, 2, 10),
    ),
    Member(
        memberId="M005",
        firstName="Margaret",
        lastName="Taylor",
        email="margaret.taylor@example.org",
        memberType="senior",
        suspendedUntil=None,
        createdAt=date(2017, 1, 5),
    ),
    Member(
        memberId="M006",
        firstName="David",
        lastName="Miller",
        email="david.miller@example.org",
        memberType="adult",
        suspendedUntil=None,
        createdAt=date(2020, 8, 19),
    ),
    Member(
        memberId="M007",
        firstName="Olivia",
        lastName="Anderson",
        email="olivia.anderson@example.org",
        memberType="student",
        suspendedUntil=None,
        createdAt=date(2022, 10, 3),
    ),
    Member(
        memberId="M008",
        firstName="Robert",
        lastName="Thompson",
        email="robert.thompson@example.org",
        memberType="adult",
        suspendedUntil=date(2024, 12, 1),
        createdAt=date(2016, 4, 18),
    ),
    Member(
        memberId="M009",
        firstName="Hannah",
        lastName="Wilson",
        email="hannah.wilson@example.org",
        memberType="student",
        suspendedUntil=None,
        createdAt=date(2025, 1, 20),
    ),
    Member(
        memberId="M010",
        firstName="James",
        lastName="Moore",
        email="james.moore@example.org",
        memberType="adult",
        suspendedUntil=None,
        createdAt=date(2015, 7, 9),
    ),
    Member(
        memberId="M011",
        firstName="Laura",
        lastName="Clark",
        email="laura.clark@example.org",
        memberType="adult",
        suspendedUntil=None,
        createdAt=date(2021, 5, 14),
    ),
    Member(
        memberId="M012",
        firstName="Ethan",
        lastName="Lewis",
        email="ethan.lewis@example.org",
        memberType="student",
        suspendedUntil=None,
        createdAt=date(2023, 1, 11),
    ),
    Member(
        memberId="M013",
        firstName="Patricia",
        lastName="Walker",
        email="patricia.walker@example.org",
        memberType="senior",
        suspendedUntil=None,
        createdAt=date(2014, 9, 2),
    ),
    Member(
        memberId="M014",
        firstName="Benjamin",
        lastName="Hall",
        email="benjamin.hall@example.org",
        memberType="adult",
        suspendedUntil=None,
        createdAt=date(2019, 11, 27),
    ),
    Member(
        memberId="M015",
        firstName="Chloe",
        lastName="Young",
        email="chloe.young@example.org",
        memberType="student",
        suspendedUntil=date(2025, 6, 30),
        createdAt=date(2022, 2, 18),
    ),
]
